### PR TITLE
Trap exit to shutdown correctly

### PR DESCRIPTION
**Pull request by alexcastano**
Related to #44. We have to capture the exit signal to shut down correctly. I also added `shutdown: :infinity` because it is the default for supervisor, and because it has a supervisor child it makes sense to me.

### CODE REVIEW

**Comment by general-CbIC** [comment]
Hello!

Thank you!

I want to ask you, does it make sense to add a flag with `:trap_exit` without handling the `EXIT` message?

**Comment by alexcastano** [comment]
> Hello!
> 
> Thank you!
> 
> I want to ask you, does it make sense to add a flag with `:trap_exit` without handling the `EXIT` message?

Genserver calls the `terminate` callback when this happens

**Comment by general-CbIC** [comment]
Looks like you're right! I missed this nuance in the documentation.

Confirmed this logic by adding the following test:
```elixir
    test "workers stop before the pool with reason :exit", %{pool_name: pool_name} do
      Process.flag(:trap_exit, true)

      {:ok, pool_pid} =
        Poolex.start(pool_id: pool_name, worker_module: SomeWorker, workers_count: 1)

      state = Poolex.get_state(pool_name)

      supervisor_pid = state.supervisor
      worker_pid = Poolex.run!(pool_name, fn pid -> pid end)

      pool_monitor_ref = Process.monitor(pool_pid)
      supervisor_monitor_ref = Process.monitor(supervisor_pid)
      worker_monitor_ref = Process.monitor(worker_pid)

      Process.exit(pool_pid, :exit)
      :timer.sleep(10)

      {:messages, [message_1, message_2, message_3]} = Process.info(self(), :messages)

      assert message_1 == {:DOWN, worker_monitor_ref, :process, worker_pid, :shutdown}

      assert elem(message_2, 0) == :DOWN
      assert elem(message_2, 1) == supervisor_monitor_ref
      assert elem(message_2, 2) == :process
      assert elem(message_2, 3) == supervisor_pid

      assert elem(message_3, 0) == :DOWN
      assert elem(message_3, 1) == pool_monitor_ref
      assert elem(message_3, 2) == :process
      assert elem(message_3, 3) == pool_pid
    end
```

I have not managed to stabilize the tests yet :( Looks like there is a process race.

**Comment by general-CbIC** [comment]
Researched problems with tests and fixed them in #47

**Review by general-CbIC — APPROVED** [review]

**Pull request merged**
